version: '1.0'
name: pipeline-bolg
displayName: pipeline-bolg
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-dc4cf5d2
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - npm install -g npm@8.10.0 && npm install && yarn run docs:build && ls
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - docs/.vuepress/dist
  - name: stage-4ce379d1
    displayName: 上传制品
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
  - name: stage-57976f72
    displayName: 部署腾讯云
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID: tt
        deployArtifact:
          - source: build
            name: output
            target: /www/wwwroot/gitee
            dependArtifact: BUILD_ARTIFACT
        script: |-
          # 请在此输入部署脚本，如启动Java应用如下
          # nohup java -jar test.jar > nohup.out &
          cd /www/wwwroot/gitee&& rm -rf dist && tar -zxvf output.tar.gz && rm -rf output.tar.gz
          echo 'Hello Gitee!'
permissions:
  - role: admin
    members: []