version: '1.0'
name: pipeline-202205211
displayName: pipeline-202205211
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-21df31cd
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - npm install -g npm@8.10.0 && npm install && rm -rf ./dist && yarn run docs:build && ls
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - docs/.vuepress/dist
  - name: stage-05752a94
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
  - name: stage-fd95a902
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID: tt
        deployArtifact:
          - source: build
            name: output
            target: /www/wwwroot/gitee
            dependArtifact: BUILD_ARTIFACT
        script: |-
          # 请在此输入部署脚本，如启动Java应用如下
          # nohup java -jar test.jar > nohup.out &
           cd /www/wwwroot/gitee && rmdir dist && tar xvf output.tar.gz && rm -rf output.tar.gz
           echo 'Hello Gitee!'
permissions:
  - role: admin
    members: []
